x-environment: &default-env
  KAFKA_BROKER: 172.200.204.1:9092
  KAFKA_ZEEK_TOPIC: zeek-live-logs
  KAFKA_EVENT_LOG_TOPIC: fluentd-events
  MONITOR_INTERFACE: eth0

services:
  # Simplified Zeek monitoring using container's default network interface
  zeek-live:
    build:
      context: .
      dockerfile: Dockerfile.zeek-live-monitor
    container_name: zeek-live-monitor
    restart: unless-stopped
    volumes:
      - ./zeek-config:/config
      - ./zeek-logs:/logs
      - ./scripts:/scripts
    environment:
      <<: *default-env
    command: /scripts/zeek-live-monitor.sh
    # Use default bridge network instead of host networking
    networks:
      - zeek-network
    # Still need some capabilities for packet capture
    cap_add:
      - NET_ADMIN
      - NET_RAW
    # Enable promiscuous mode for packet capture
    privileged: true
    # Route traffic through Zeek container to enable monitoring
    ports:
      - "8082:80"  # Proxy port for monitoring web traffic

  # Simplified traffic simulator using default networking
  siem-simulator:
    build:
      context: .
      dockerfile: Dockerfile.simulator
    container_name: siem-simulator
    restart: unless-stopped
    volumes:
      - ./traffic-scripts:/traffic-scripts
    environment:
      <<: *default-env
    ports:
      - "8080:8080"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    command: python3 /traffic-scripts/simulator_server.py

  fluentd:
    image: fluent/fluentd:v1.16-1
    volumes:
      - ./logs:/logs                 # Access simulator logs
      - ./fluentd/conf:/fluentd/etc  # Mount Fluentd config
    environment:
      <<: *default-env
    restart: unless-stopped

networks:
  zeek-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24
