services:
  # Simplified Zeek monitoring using container's default network interface
  zeek-live:
    build:
      context: ./services/zeek-monitor
      dockerfile: Dockerfile
    container_name: zeek-live-monitor
    restart: unless-stopped
    volumes:
      - ./services/zeek-monitor/config:/config
      - ./services/zeek-monitor/logs:/logs
      - ./services/zeek-monitor/scripts:/scripts
    env_file: .env
    command: /scripts/zeek-live-monitor.sh
    # Use default bridge network instead of host networking
    networks:
      - zeek-network
    # Still need some capabilities for packet capture
    cap_add:
      - NET_ADMIN
      - NET_RAW
    # Enable promiscuous mode for packet capture
    privileged: true

  # Simplified traffic simulator using default networking
  siem-simulator:
    build:
      context: ./services/simulator
      dockerfile: Dockerfile
    container_name: siem-simulator
    restart: unless-stopped
    volumes:
      - ./services/simulator/src:/src/simulator
      - ./services/fluentd/logs:/logs
    env_file: .env
    ports:
      - "8080:8080"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      - zeek-network
    command: python3 /src/simulator/simulator_server.py

  fluentd:
    build:
      context: ./services/fluentd
      dockerfile: Dockerfile
    container_name: fluentd
    restart: unless-stopped
    image: fluentd:custom
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - ./services/fluentd/conf:/fluentd/etc
      - ./services/fluentd/logs:/logs
    environment:
      - FLUENTD_CONF=fluentd.conf
    env_file: .env

networks:
  zeek-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24
